In [1]:
import pandas as pd

In [2]:
## loading the phase 2 dataset
df = pd.read_csv('../data/phase2_churn_label_creation.csv')

#### Decrease in usage

In [3]:
## outgoing usage drop
df['og_usage_avg_6_7'] = (df['total_og_mou_6'] + df['total_og_mou_7']) / 2

df['og_usage_drop'] = df['total_og_mou_8'] - df['og_usage_avg_6_7']


## incoming usage drop
df['ic_usage_avg_6_7'] = (df['total_ic_mou_6'] + df['total_ic_mou_7']) / 2

df['ic_usage_drop'] = df['total_ic_mou_8'] - df['ic_usage_avg_6_7']

In [4]:
## to find the data usage now we will be combining the usage of 2g and 3g across months 6,7 and 8

df['data_usage_6'] = df['vol_2g_mb_6'] + df['vol_3g_mb_6']
df['data_usage_7'] = df['vol_2g_mb_7'] + df['vol_3g_mb_7']
df['data_usage_8'] = df['vol_2g_mb_8'] + df['vol_3g_mb_8']

In [5]:
##avg of month 6 and 7

df['data_avg_6_7'] = (df['data_usage_6'] + df['data_usage_7']) / 2

In [6]:
## now check for usage change

df['data_usage_drop'] = df['data_usage_8'] - df['data_avg_6_7']

In [7]:
df.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,...,churn,og_usage_avg_6_7,og_usage_drop,ic_usage_avg_6_7,ic_usage_drop,data_usage_6,data_usage_7,data_usage_8,data_avg_6_7,data_usage_drop
0,7000701601,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,1069.180,1349.850,...,1,548.385,-198.225,592.250,-163.510,0.0,0.00,0.00,0.000,0.000
1,7001524846,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,378.721,492.223,...,0,470.010,-298.450,66.175,-49.635,0.0,1106.95,11.97,553.475,-541.505
2,7002191713,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,492.846,205.671,...,0,549.750,465.510,570.595,573.935,0.0,0.00,0.02,0.000,0.020
3,7000875565,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,430.975,299.869,...,0,316.410,-83.030,373.210,-78.750,0.0,0.00,0.00,0.000,0.000
4,7000187447,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,690.008,18.980,...,0,625.170,-625.170,47.095,-47.095,0.0,0.00,0.00,0.000,0.000

In [8]:
df.tail()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,...,churn,og_usage_avg_6_7,og_usage_drop,ic_usage_avg_6_7,ic_usage_drop,data_usage_6,data_usage_7,data_usage_8,data_avg_6_7,data_usage_drop
30006,7001386760,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,261.269,410.614,...,0,466.56,-13.35,148.380,153.030,0.00,0.00,0.00,0.000,0.000
30007,7001453306,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,414.303,321.093,...,0,410.76,-46.83,108.675,-55.545,0.00,0.00,0.00,0.000,0.000
30008,7001729035,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,644.973,455.228,...,0,1392.00,-11.99,601.505,58.505,770.29,1145.75,933.25,958.020,-24.770
30009,7002111859,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,312.558,512.932,...,0,413.63,-162.84,686.970,546.860,0.00,13.56,679.53,6.780,672.750
30010,7000498689,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,322.991,303.386,...,0,0.00,0.00,5.950,-3.660,1530.14,1623.85,2819.77,1576.995,1242.775

#### Feature 2 — Recharge Frequency Drop

In [9]:
## Customers who churn often stop recharging frequently

## avg recharge count

df['rech_cnt_avg_6_7'] = (df['total_rech_num_6'] + df['total_rech_num_7']) / 2

In [10]:
## -ve value means customer is recharging less often.

df['rech_freq_drop'] = df['total_rech_num_8'] - df['rech_cnt_avg_6_7']

In [11]:
df.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,...,og_usage_drop,ic_usage_avg_6_7,ic_usage_drop,data_usage_6,data_usage_7,data_usage_8,data_avg_6_7,data_usage_drop,rech_cnt_avg_6_7,rech_freq_drop
0,7000701601,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,1069.180,1349.850,...,-198.225,592.250,-163.510,0.0,0.00,0.00,0.000,0.000,5.0,2.0
1,7001524846,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,378.721,492.223,...,-298.450,66.175,-49.635,0.0,1106.95,11.97,553.475,-541.505,20.0,-6.0
2,7002191713,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,492.846,205.671,...,465.510,570.595,573.935,0.0,0.00,0.02,0.000,0.020,5.0,6.0
3,7000875565,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,430.975,299.869,...,-83.030,373.210,-78.750,0.0,0.00,0.00,0.000,0.000,8.0,-6.0
4,7000187447,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,690.008,18.980,...,-625.170,47.095,-47.095,0.0,0.00,0.00,0.000,0.000,10.5,-6.5

In [12]:
df.tail()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,...,og_usage_drop,ic_usage_avg_6_7,ic_usage_drop,data_usage_6,data_usage_7,data_usage_8,data_avg_6_7,data_usage_drop,rech_cnt_avg_6_7,rech_freq_drop
30006,7001386760,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,261.269,410.614,...,-13.35,148.380,153.030,0.00,0.00,0.00,0.000,0.000,15.0,-2.0
30007,7001453306,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,414.303,321.093,...,-46.83,108.675,-55.545,0.00,0.00,0.00,0.000,0.000,7.5,-4.5
30008,7001729035,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,644.973,455.228,...,-11.99,601.505,58.505,770.29,1145.75,933.25,958.020,-24.770,7.0,-4.0
30009,7002111859,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,312.558,512.932,...,-162.84,686.970,546.860,0.00,13.56,679.53,6.780,672.750,12.0,-3.0
30010,7000498689,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,322.991,303.386,...,0.00,5.950,-3.660,1530.14,1623.85,2819.77,1576.995,1242.775,3.5,0.5

#### Feature 3 — Recharge Amount Drop

In [13]:
## Customers may start spending less.

df['rech_amt_avg_6_7'] = (df['total_rech_amt_6'] + df['total_rech_amt_7']) / 2

df['rech_amt_drop'] = df['total_rech_amt_8'] - df['rech_amt_avg_6_7']

In [14]:
df.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,...,ic_usage_drop,data_usage_6,data_usage_7,data_usage_8,data_avg_6_7,data_usage_drop,rech_cnt_avg_6_7,rech_freq_drop,rech_amt_avg_6_7,rech_amt_drop
0,7000701601,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,1069.180,1349.850,...,-163.510,0.0,0.00,0.00,0.000,0.000,5.0,2.0,1185.0,2453.0
1,7001524846,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,378.721,492.223,...,-49.635,0.0,1106.95,11.97,553.475,-541.505,20.0,-6.0,519.0,-399.0
2,7002191713,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,492.846,205.671,...,573.935,0.0,0.00,0.02,0.000,0.020,5.0,6.0,380.0,337.0
3,7000875565,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,430.975,299.869,...,-78.750,0.0,0.00,0.00,0.000,0.000,8.0,-6.0,459.0,-299.0
4,7000187447,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,690.008,18.980,...,-47.095,0.0,0.00,0.00,0.000,0.000,10.5,-6.5,408.0,-378.0

#### Feature 4 — Data vs Voice Behaviour

In [15]:
## maybe data usage drops but voice stays stable.

## compute voice average

df['voice_usage_6'] = df['total_og_mou_6'] + df['total_ic_mou_6']
df['voice_usage_7'] = df['total_og_mou_7'] + df['total_ic_mou_7']
df['voice_usage_8'] = df['total_og_mou_8'] + df['total_ic_mou_8']

df['voice_avg_6_7'] = (df['voice_usage_6'] + df['voice_usage_7']) / 2

In [16]:
## voice change

df['voice_usage_drop'] = df['voice_usage_8'] - df['voice_avg_6_7']

In [17]:
## data v/s voice ratio
## +1 is the correction factor, helps in handling 0 in Denominator.

df['data_voice_ratio_8'] = df['data_usage_8'] / (df['voice_usage_8'] + 1)

In [18]:
df.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,...,rech_cnt_avg_6_7,rech_freq_drop,rech_amt_avg_6_7,rech_amt_drop,voice_usage_6,voice_usage_7,voice_usage_8,voice_avg_6_7,voice_usage_drop,data_voice_ratio_8
0,7000701601,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,1069.180,1349.850,...,5.0,2.0,1185.0,2453.0,1113.99,1167.28,778.90,1140.635,-361.735,0.000000
1,7001524846,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,378.721,492.223,...,20.0,-6.0,519.0,-399.0,612.22,460.15,188.10,536.185,-348.085,0.063300
2,7002191713,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,492.846,205.671,...,5.0,6.0,380.0,337.0,1875.70,364.99,2159.79,1120.345,1039.445,0.000009
3,7000875565,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,430.975,299.869,...,8.0,-6.0,459.0,-299.0,711.67,667.57,527.84,689.620,-161.780,0.000000
4,7000187447,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,690.008,18.980,...,10.5,-6.5,408.0,-378.0,1341.41,3.12,0.00,672.265,-672.265,0.000000

In [19]:
df.tail()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,...,rech_cnt_avg_6_7,rech_freq_drop,rech_amt_avg_6_7,rech_amt_drop,voice_usage_6,voice_usage_7,voice_usage_8,voice_avg_6_7,voice_usage_drop,data_voice_ratio_8
30006,7001386760,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,261.269,410.614,...,15.0,-2.0,392.0,-55.0,313.47,916.41,754.62,614.940,139.680,0.000000
30007,7001453306,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,414.303,321.093,...,7.5,-4.5,465.0,-77.0,569.05,469.82,417.06,519.435,-102.375,0.000000
30008,7001729035,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,644.973,455.228,...,7.0,-4.0,848.5,-823.5,2181.52,1805.49,2040.02,1993.505,46.515,0.457247
30009,7002111859,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,312.558,512.932,...,12.0,-3.0,467.0,37.0,1374.74,826.46,1484.62,1100.600,384.020,0.457405
30010,7000498689,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,322.991,303.386,...,3.5,0.5,369.5,346.5,0.81,11.09,2.29,5.950,-3.660,857.072948

In [20]:
## handling the missing values

df = df.fillna(0)

In [21]:
df.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,...,rech_cnt_avg_6_7,rech_freq_drop,rech_amt_avg_6_7,rech_amt_drop,voice_usage_6,voice_usage_7,voice_usage_8,voice_avg_6_7,voice_usage_drop,data_voice_ratio_8
0,7000701601,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,1069.180,1349.850,...,5.0,2.0,1185.0,2453.0,1113.99,1167.28,778.90,1140.635,-361.735,0.000000
1,7001524846,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,378.721,492.223,...,20.0,-6.0,519.0,-399.0,612.22,460.15,188.10,536.185,-348.085,0.063300
2,7002191713,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,492.846,205.671,...,5.0,6.0,380.0,337.0,1875.70,364.99,2159.79,1120.345,1039.445,0.000009
3,7000875565,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,430.975,299.869,...,8.0,-6.0,459.0,-299.0,711.67,667.57,527.84,689.620,-161.780,0.000000
4,7000187447,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,690.008,18.980,...,10.5,-6.5,408.0,-378.0,1341.41,3.12,0.00,672.265,-672.265,0.000000

In [22]:
df[['og_usage_drop',
    'ic_usage_drop',
    'data_usage_drop',
    'rech_freq_drop',
    'rech_amt_drop',
    'voice_usage_drop']].describe()

,og_usage_drop,ic_usage_drop,data_usage_drop,rech_freq_drop,rech_amt_drop,voice_usage_drop
count,30011.000000,30011.000000,30011.000000,30011.000000,30011.000000,30011.000000
mean,-74.136452,-15.767241,-7.685188,-1.792076,-83.025557,-89.903693
std,522.991551,223.521778,603.834757,6.946601,424.891218,625.873083
min,-7213.410000,-3316.590000,-12423.930000,-147.500000,-6950.000000,-7412.170000
25%,-217.340000,-75.382500,-0.272500,-4.000000,-273.000000,-304.490000
50%,-35.440000,-9.110000,0.000000,-1.500000,-71.000000,-48.585000
75%,95.047500,47.675000,0.000000,1.000000,105.000000,147.277500
max,12768.705000,4862.625000,15335.560000,130.500000,14344.500000,12790.270000

In [23]:
print(df.columns)

Index(['mobile_number', 'circle_id', 'loc_og_t2o_mou', 'std_og_t2o_mou',
       'loc_ic_t2o_mou', 'last_date_of_month_6', 'last_date_of_month_7',
       'last_date_of_month_8', 'arpu_6', 'arpu_7',
       ...
       'rech_cnt_avg_6_7', 'rech_freq_drop', 'rech_amt_avg_6_7',
       'rech_amt_drop', 'voice_usage_6', 'voice_usage_7', 'voice_usage_8',
       'voice_avg_6_7', 'voice_usage_drop', 'data_voice_ratio_8'],
      dtype='object', length=193)

In [24]:
df.to_csv("../data/phase3_feature_engineering.csv", index = False)