In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/phase3_feature_engineering.csv')

In [3]:
df.shape

(30011, 193)

In [4]:
df.head()

,mobile_number,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,...,rech_cnt_avg_6_7,rech_freq_drop,rech_amt_avg_6_7,rech_amt_drop,voice_usage_6,voice_usage_7,voice_usage_8,voice_avg_6_7,voice_usage_drop,data_voice_ratio_8
0,7000701601,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,1069.180,1349.850,...,5.0,2.0,1185.0,2453.0,1113.99,1167.28,778.90,1140.635,-361.735,0.000000
1,7001524846,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,378.721,492.223,...,20.0,-6.0,519.0,-399.0,612.22,460.15,188.10,536.185,-348.085,0.063300
2,7002191713,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,492.846,205.671,...,5.0,6.0,380.0,337.0,1875.70,364.99,2159.79,1120.345,1039.445,0.000009
3,7000875565,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,430.975,299.869,...,8.0,-6.0,459.0,-299.0,711.67,667.57,527.84,689.620,-161.780,0.000000
4,7000187447,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,690.008,18.980,...,10.5,-6.5,408.0,-378.0,1341.41,3.12,0.00,672.265,-672.265,0.000000

In [5]:
# X --> features

# y --> target (churn)

X = df.drop(columns=['churn','mobile_number'])
y = df['churn']

In [6]:
X

,circle_id,loc_og_t2o_mou,std_og_t2o_mou,loc_ic_t2o_mou,last_date_of_month_6,last_date_of_month_7,last_date_of_month_8,arpu_6,arpu_7,arpu_8,...,rech_cnt_avg_6_7,rech_freq_drop,rech_amt_avg_6_7,rech_amt_drop,voice_usage_6,voice_usage_7,voice_usage_8,voice_avg_6_7,voice_usage_drop,data_voice_ratio_8
0,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,1069.180,1349.850,3171.480,...,5.0,2.0,1185.0,2453.0,1113.99,1167.28,778.90,1140.635,-361.735,0.000000
1,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,378.721,492.223,137.362,...,20.0,-6.0,519.0,-399.0,612.22,460.15,188.10,536.185,-348.085,0.063300
2,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,492.846,205.671,593.260,...,5.0,6.0,380.0,337.0,1875.70,364.99,2159.79,1120.345,1039.445,0.000009
3,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,430.975,299.869,187.894,...,8.0,-6.0,459.0,-299.0,711.67,667.57,527.84,689.620,-161.780,0.000000
4,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,690.008,18.980,25.499,...,10.5,-6.5,408.0,-378.0,1341.41,3.12,0.00,672.265,-672.265,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30006,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,261.269,410.614,290.851,...,15.0,-2.0,392.0,-55.0,313.47,916.41,754.62,614.940,139.680,0.000000
30007,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,414.303,321.093,371.016,...,7.5,-4.5,465.0,-77.0,569.05,469.82,417.06,519.435,-102.375,0.000000
30008,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,644.973,455.228,564.334,...,7.0,-4.0,848.5,-823.5,2181.52,1805.49,2040.02,1993.505,46.515,0.457247
30009,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,312.558,512.932,402.080,...,12.0,-3.0,467.0,37.0,1374.74,826.46,1484.62,1100.600,384.020,0.457405
30010,109,0.0,0.0,0.0,6/30/2014,7/31/2014,8/31/2014,322.991,303.386,606.817,...,3.5,0.5,369.5,346.5,0.81,11.09,2.29,5.950,-3.660,857.072948

In [7]:
y

0        1
1        0
2        0
3        0
4        0
        ..
30006    0
30007    0
30008    0
30009    0
30010    0
Name: churn, Length: 30011, dtype: int64

In [8]:
## checking the class distribution
y.value_counts()

churn
0    27418
1     2593
Name: count, dtype: int64

In [9]:
y.value_counts(normalize = True)*100

churn
0    91.359835
1     8.640165
Name: proportion, dtype: float64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [12]:
cols_to_drop = X_train.select_dtypes(include='object').columns

X_train = X_train.drop(columns=cols_to_drop)
X_test = X_test.drop(columns=cols_to_drop)

In [13]:
X_train.dtypes.value_counts()

float64    156
int64       26
Name: count, dtype: int64

In [14]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state=42)

X_train_resampled, y_train_resampled = smote.fit_resample(X_train, y_train)

In [15]:
y_train_resampled.value_counts()

churn
0    21934
1    21934
Name: count, dtype: int64